### ISSUE TITLE
install does not work under mint 19.2

### ISSUE THREAD

**Issue by hugocoolens** [funbox/optimizt#23]
I have attached the log-file which shows installation under mint 19.2 fails
[npm-debug.log](https://github.com/funbox/optimizt/files/6584800/npm-debug.log)

**Comment by igoradamenko** [comment]
Hey there.

I'm not sure that it's Optimizt's fault. According to your log file, you're using Node.js 8.10 & npm 3.5.2. Both are obsolete and no longer maintained. And it looks like there is a bug somewhere in them. Check this issue: https://github.com/npm/cli/issues/681.

As I understand, the fastest way to fix it is to update your Node.js & npm. Would you mind to try to update and then install Optimizt again?

**Comment by hugocoolens** [comment]
>As I understand, the fastest way to fix it is to update your Node.js & npm. Would you mind to try to update and then install >Optimizt again?
I am a bit afraid to end with broken dependencies when I'd try to update those outside the Mint package install system. I'll try it
again once I have installed the latest Mint.

**Comment by igoradamenko** [comment]
@hugocoolens, any news?

**Comment by igoradamenko** [comment]
Feel free to reopen if the problem occurs.
