### ISSUE TITLE
Bash command is incorrect

### ISSUE THREAD

**Issue by eduardfossas** [funbox/optimizt#28]
To apply recursively the optimisation in a folder it should be:
`find . -type f -name '*.jpg' -exec optimizt {} \;`

instead of:
optimizt `find . -type f -name '*.jpg'`

**Comment by 343dev** [comment]
Hi. Thanks for your suggestion.
Fixed in #29.

> To apply recursively the optimisation in a folder it should be:
> `find . -type f -name '*.jpg' -exec optimizt {} \;`

This will execute Optimizt once for each file:

```
find . -type f -name '*.jpg' -exec optimizt {} \;
ℹ Optimizing 1 image (lossy)...
✔ ./00d963b5c9a1441ef76569709154f90e00a4a0c7_80_45_c.jpg
   2.771 KB → 1.746 KB. Ratio: 37%

ℹ Yay! You saved 1.024 KB (37%)
ℹ Optimizing 1 image (lossy)...
✔ ./6b64eb197de1e5caa18e6b1d2fd99b6a_100_100.jpg
   5.817 KB → 2.901 KB. Ratio: 50%

ℹ Yay! You saved 2.916 KB (50%)
ℹ Optimizing 1 image (lossy)...
✔ ./6f25bfbb155370c12518f0ca0e5052c2_48_48_c.jpg
   1.83 KB → 1.138 KB. Ratio: 38%

ℹ Yay! You saved 709 Bytes (38%)
```

To execute Optimizt once with all the files as arguments we should use:

```
find . -name '*.jpg' -exec optimizt {} +
```
