### ISSUE TITLE
Does it work on m1 macbooks?

### ISSUE THREAD

**Issue by boringcoding** [funbox/optimizt#30]
I'm getting 
`npm ERR! Cannot find libjpeg or you have too old version (v6 or later required).`
But I have libjpeg installed via homebrew.

**Comment by boringcoding** [comment]
I managed to install it like this:
`CPPFLAGS="-I /opt/homebrew/Cellar/jpeg/9d/include" LDFLAGS="-L /opt/homebrew/Cellar/jpeg/9d/lib" npm i -g @funboxteam/optimizt`

**Comment by iamandrewluca** [comment]
For me I had to replace in path `9d` with `9e`

**Comment by 343dev** [comment]
Yes, it depends on the version of libjpeg you have installed.

```sh
brew info libjpeg

jpeg: stable 9e (bottled)
Image manipulation library
https://www.ijg.org/
/opt/homebrew/Cellar/jpeg/9e (21 files, 904.2KB) *
  Poured from bottle on 2022-03-02 at 00:56:01
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/jpeg.rb
License: IJG
```
