### ISSUE TITLE
deprecated uuid@3.4.0

### ISSUE THREAD

**Issue by SergioChizhikov** [funbox/optimizt#31]
Hi,
work fine. Thank you a lot! Very Nice job. When installing I`m see - deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.

**Comment by igoradamenko** [comment]
Hey there.

It's fine. We don't use uuid directly. It's coming from the several dep chains. E.g. one of them is `guetzli → bin-build → tempfile → uuid`.

Deprecation does not mean “it's broken”, so it is not a big deal.
