### ISSUE TITLE
Failure to install from version 4.1.0

### ISSUE THREAD

**Issue by alistairstead** [funbox/optimizt#59]
The latest release references a local path `file:guetzli-5.0.0.tgz` this does not appear to be part of the published package and all attempts to install fail.

OS: Mac OS 13.2
Node version: 16.19.0
Package managers tried: npm & pnpm

Pinning to `4.0.0` resolves all install issues.

**Comment by igoradamenko** [comment]
Hey.

It should be fixed in @funboxteam/optimizt@4.1.1.

Thank you for the report 👍

**Comment by alistairstead** [comment]
Thanks for the fix
